@file:Suppress("MagicNumber")

package com.balaji.callhistory.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Automatically generated by the Material Theme Builder from the following core colors:
 *
 * coreColors": {
 *     "primary": "#26508E",
 *     "secondary": "#A8D7FD",
 *     "tertiary": "#0A7DDA",
 *     "error": "#F7A1A1",
 *     "neutral": "#F2F2F2",
 *     "neutralVariant": "#909394"
 * }
 *
 * @see <a href="https://material-foundation.github.io/material-theme-builder/">Material Theme Builder</a>
 */

val primaryLight = Color(0xFF26508E) //Primäre Aktionen
val onPrimaryLight = Color(0xFFFFFFFF) //Text primärer Button
val primaryContainerLight = Color(0xFFD3E3FF)
val onPrimaryContainerLight = Color(0xFF26508E)
val secondaryLight = Color(0xFFA8D7FD) // sekundäre Aktion
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCAE6FF)
val onSecondaryContainerLight = Color(0xFF001E2F)
val tertiaryLight = Color(0xFF4CAF50)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD7E3FF)
val onTertiaryContainerLight = Color(0xFF001B3E)
val errorLight = Color(0xFFB71C1C)
val onErrorLight = Color(0xFFFAFAFA)
val errorContainerLight = Color(0xFFFF8A80)
val onErrorContainerLight = Color(0xFF3B080D)
val backgroundLight = Color(0xFFEEEEEE)
val onBackgroundLight = Color(0xFF212121)
val surfaceLight = Color(0xFFEEEEEE)
val onSurfaceLight = Color(0xFF212121)
val surfaceVariantLight = Color(0xFF757575)
val onSurfaceVariantLight = Color(0xFF3F484B)
val outlineLight = Color(0xFFBDBDBD)
val outlineVariantLight = Color(0xFFBDBDBD)
val scrimLight = Color(0xFF3F484B) //transparenter BG bei Sheets
val inverseSurfaceLight = Color(0xFFFB8C00)
val inverseOnSurfaceLight = Color(0xFFFDD835)
val inversePrimaryLight = Color(0xFFA4C9FE)
val surfaceDimLight = Color(0xFFFAFAFA)
val surfaceBrightLight = Color(0xFF00ACC1)
val surfaceContainerLowestLight = Color(0xFFC0CA33)
val surfaceContainerLowLight = Color(0xFFFAFAFA)
val surfaceContainerLight = Color(0xFFFAFAFA)
val surfaceContainerHighLight = Color(0xFFFAFAFA)
val surfaceContainerHighestLight = Color(0xFFFFFFFF)

val disableButtonColorLight = Color(0xFF585858)
val dangerButtonTextColorLight = Color(0xFF850D0B)
val actionIconColorLight = Color(0xFF3388FF)
val actionIconColorDark = Color(0XFF2C6EF4)
val menuIconColorLight = Color(0xFF3388FF)
val menuIconColorDark = Color(0XFF2C6EF4)
val nonActionIconColorLight = Color(0xFF000000)
val nonActionIconColorDark = Color(0xFFFFFFFF)


val primaryDark = Color(0xFF01579B)
val onPrimaryDark = Color(0xFFE1F5FE)
val primaryContainerDark = Color(0xFFB3E5FC)
val onPrimaryContainerDark = Color(0xFF01579B)
val secondaryDark = Color(0xFF01579B)
val onSecondaryDark = Color(0xFFB3E5FC)
val secondaryContainerDark = Color(0xFFB3E5FC)
val onSecondaryContainerDark = Color(0xFF01579B)
val tertiaryDark = Color(0xFFFDD835)
val onTertiaryDark = Color(0xFFFFB300)
val tertiaryContainerDark = Color(0xFFFB8C00)
val onTertiaryContainerDark = Color(0xFFFB8C00)
val errorDark = Color(0xFFFFB3B2)
val onErrorDark = Color(0xFF561D20)
val errorContainerDark = Color(0xFF733335)
val onErrorContainerDark = Color(0xFF8E24AA)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFFAFAFA)
val surfaceDark = Color(0xFF000000)
val onSurfaceDark = Color(0xFFFAFAFA)
val surfaceVariantDark = Color(0xFFFAFAFA)
val onSurfaceVariantDark = Color(0xFFEEEEEE)
val outlineDark = Color(0xFF899295)
val outlineVariantDark = Color(0xFF424242)
val scrimDark = Color(0xFF212121)
val inverseSurfaceDark = Color(0xFF43A047)
val inverseOnSurfaceDark = Color(0xFF00897B)
val inversePrimaryDark = Color(0xFF00ACC1)
val surfaceDimDark = Color(0xFF1E88E5)
val surfaceBrightDark = Color(0xFF1E88E5)
val surfaceContainerLowestDark = Color(0xFF3949AB)
val surfaceContainerLowDark = Color(0xFF212121)
val surfaceContainerDark = Color(0xFF212121)
val surfaceContainerHighDark = Color(0xFF212121)
val surfaceContainerHighestDark = Color(0xFF000000)

val textButtonColorDark = Color(0xFF068CF9)
val cardColorDark = Color(0xFF1B1C1D)
val listColorDark = Color(0xFF1B1C1D)
val badgeBlueIndicatorColorDark = Color(0xFF12508E)
val badgeRedIndicatorColorDark = Color(0xFF8D2F2C)
val disableButtonColorDark = Color(0xFF888888)
val bottomBarListIconColorDark = Color(0xFF888888)
val detailPageTabColorDark = Color(0xFF068CF9)
val dangerButtonTextColorDark = Color(0xFF850D0B)

val mutedBackgroundColorDark = Color(0xFF555559)

val successBackgroundColorDark = Color(0xFF26773B)

val warningBackgroundColorDark = Color(0xFF8C5E14)

